debug: true

tg_token:

openai_token:

aws_access_key_id:
aws_secret_access_key: 
aws_region:

sqs_url:
sqs_queue_name:

dynamodb_table_name:

s3_bucket_name:

# debug -> info -> warn -> error
logger:
  log_level: 'debug'