debug: true

tg_token:
user_password:

aws_access_key_id:
aws_secret_access_key:
aws_region:

sqs_queue_name: 

voice_queries_table_name: 
chats_table_name:


# debug -> info -> warn -> error
logger:
  log_level: 'debug'